### ISSUE TITLE
descartes 1.2.5 doesn't work with pitest 1.4.10

### ISSUE THREAD

**Issue by MasterFocus** [STAMP-project/pitest-descartes#109]
**What worked:**

:heavy_check_mark: descartes 1.2.5 + pitest 1.4.8
:heavy_check_mark: descartes 1.2.5 + pitest 1.4.9
:x: descartes 1.2.5 + pitest 1.4.10

**Additional details:**
- JDK 8
- JUnit 5 (simple tests, nothing fancy)

**Relevant log:**

```
18:01:29 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
18:01:30 PIT >> INFO : Sending 115 test classes to minion
18:01:30 PIT >> INFO : Sent tests to minion
18:01:30 PIT >> INFO : MINION : 18:01:30 PIT >> INFO : Checking environment

18:01:30 PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.pitest.coverage.BlockLocation.<init>(Lorg/pitest/mutationtest/engine/Location;III)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:138)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
	at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:466)
	at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:407)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.NoSuchMethodError: org.pitest.coverage.BlockLocation.<init>(Lorg/pitest/mutationtest/engine/Location;III)V
	at org.pitest.coverage.execute.Receive.handleProbes(Receive.java:64)
	at org.pitest.coverage.execute.Receive.apply(Receive.java:42)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:57)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:35)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
18:01:30 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
```

**Comment by oscarlvp** [comment]
Version 1.2.6 works with PIT 1.4.10
